// ARCHIVO GENERADO AUTOMÁTICAMENTE. No editar a mano.
// Fuente: datos_ppl_ficticios.csv  —  DATOS 100 % FICTICIOS.
// Para regenerarlo: python3 herramientas/csv_a_js.py
window.FUENTE_PPL_EMBEBIDA = [
 {
  "ID": 1,
  "Nombre completo": "Karina Garza Villaseñor",
  "Expediente": "EXP-FIC-1000/2020",
  "Causa penal": "CP-FIC-100/2020",
  "Delito": "Secuestro",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Norte (ficticio)",
  "Pena en años": 9,
  "Fecha de sentencia": "2023-02-17",
  "Fecha de inicio": "2020-10-23",
  "Fecha de cumplimiento": "2029-10-23",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 2,
  "Nombre completo": "Fabiola Tapia Sandoval",
  "Expediente": "EXP-FIC-1007/2013",
  "Causa penal": "CP-FIC-101/2013",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Región Centro (ficticio)",
  "Pena en años": 10,
  "Fecha de sentencia": "2013-11-04",
  "Fecha de inicio": "2013-03-11",
  "Fecha de cumplimiento": "2023-03-11",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 3,
  "Nombre completo": "Gerardo Galindo Contreras",
  "Expediente": "EXP-FIC-1014/2021",
  "Causa penal": "CP-FIC-102/2021",
  "Delito": "Secuestro",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Occidente (ficticio)",
  "Pena en años": 15,
  "Fecha de sentencia": "2022-08-21",
  "Fecha de inicio": "2021-05-18",
  "Fecha de cumplimiento": "2036-05-18",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 4,
  "Nombre completo": "Alma Delia Zavala Delgado",
  "Expediente": "EXP-FIC-1021/2020",
  "Causa penal": "CP-FIC-103/2020",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noreste (ficticio)",
  "Pena en años": 20,
  "Fecha de sentencia": "2021-08-19",
  "Fecha de inicio": "2020-05-07",
  "Fecha de cumplimiento": "2040-05-07",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 5,
  "Nombre completo": "Marco Antonio Guerrero Mejía",
  "Expediente": "EXP-FIC-1028/2023",
  "Causa penal": "CP-FIC-104/2023",
  "Delito": "Secuestro",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Desierto (ficticio)",
  "Pena en años": 21,
  "Fecha de sentencia": "2024-11-20",
  "Fecha de inicio": "2023-01-30",
  "Fecha de cumplimiento": "2044-01-28",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 6,
  "Nombre completo": "Claudia Cabrera Villaseñor",
  "Expediente": "EXP-FIC-1035/2022",
  "Causa penal": "CP-FIC-105/2022",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Regional de Reinserción Sur (ficticio)",
  "Pena en años": 9.5,
  "Fecha de sentencia": "2024-04-22",
  "Fecha de inicio": "2022-09-10",
  "Fecha de cumplimiento": "2032-03-10",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 7,
  "Nombre completo": "Samuel Estrada Barrios",
  "Expediente": "EXP-FIC-1042/2019",
  "Causa penal": "CP-FIC-106/2019",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Golfo (ficticio)",
  "Pena en años": 20.5,
  "Fecha de sentencia": "2020-03-19",
  "Fecha de inicio": "2019-08-16",
  "Fecha de cumplimiento": "2040-02-16",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 8,
  "Nombre completo": "Omar Rangel Orozco",
  "Expediente": "EXP-FIC-1049/2020",
  "Causa penal": "CP-FIC-107/2020",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Tierra Caliente (ficticio)",
  "Pena en años": 17,
  "Fecha de sentencia": "2022-01-23",
  "Fecha de inicio": "2020-03-09",
  "Fecha de cumplimiento": "2037-03-09",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 9,
  "Nombre completo": "Hilda Benítez Contreras",
  "Expediente": "EXP-FIC-1056/2015",
  "Causa penal": "CP-FIC-108/2015",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Pacífico (ficticio)",
  "Pena en años": 27,
  "Fecha de sentencia": "2017-03-19",
  "Fecha de inicio": "2015-01-27",
  "Fecha de cumplimiento": "2042-01-27",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 10,
  "Nombre completo": "César Garza Fuentes",
  "Expediente": "EXP-FIC-1063/2021",
  "Causa penal": "CP-FIC-109/2021",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Frontera (ficticio)",
  "Pena en años": 3,
  "Fecha de sentencia": "2023-01-04",
  "Fecha de inicio": "2021-03-17",
  "Fecha de cumplimiento": "2024-03-17",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 11,
  "Nombre completo": "Salvador Garza Medina",
  "Expediente": "EXP-FIC-1070/2016",
  "Causa penal": "CP-FIC-110/2016",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Oriente (ficticio)",
  "Pena en años": 18,
  "Fecha de sentencia": "2017-09-21",
  "Fecha de inicio": "2016-10-07",
  "Fecha de cumplimiento": "2034-10-07",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 12,
  "Nombre completo": "Araceli Maldonado Tapia",
  "Expediente": "EXP-FIC-1077/2015",
  "Causa penal": "CP-FIC-111/2015",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Estatal Valle Alto (ficticio)",
  "Pena en años": 28,
  "Fecha de sentencia": "2016-06-18",
  "Fecha de inicio": "2015-10-06",
  "Fecha de cumplimiento": "2043-10-06",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 13,
  "Nombre completo": "Cristian Bautista Delgado",
  "Expediente": "EXP-FIC-1084/2014",
  "Causa penal": "CP-FIC-112/2014",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Occidente (ficticio)",
  "Pena en años": 9,
  "Fecha de sentencia": "2016-03-09",
  "Fecha de inicio": "2014-10-10",
  "Fecha de cumplimiento": "2023-10-10",
  "Observaciones": "Persona ficticia con dos causas penales distintas."
 },
 {
  "ID": 14,
  "Nombre completo": "Salvador Gallardo Zamora",
  "Expediente": "EXP-FIC-1091/2017",
  "Causa penal": "CP-FIC-113/2017",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Sierra Madre (ficticio)",
  "Pena en años": 19,
  "Fecha de sentencia": "2019-12-18",
  "Fecha de inicio": "2017-11-20",
  "Fecha de cumplimiento": "2036-11-20",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 15,
  "Nombre completo": "Javier Castañeda Cabrera",
  "Expediente": "EXP-FIC-1098/2019",
  "Causa penal": "CP-FIC-114/2019",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Desierto (ficticio)",
  "Pena en años": 36,
  "Fecha de sentencia": "2020-04-25",
  "Fecha de inicio": "2019-04-04",
  "Fecha de cumplimiento": "2055-04-04",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 16,
  "Nombre completo": "Sergio Fuentes Velasco",
  "Expediente": "EXP-FIC-1105/2018",
  "Causa penal": "CP-FIC-115/2018",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Volcanes (ficticio)",
  "Pena en años": 6,
  "Fecha de sentencia": "2020-05-14",
  "Fecha de inicio": "2018-01-19",
  "Fecha de cumplimiento": "2024-01-19",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 17,
  "Nombre completo": "Alfonso Palacios Ibarra",
  "Expediente": "EXP-FIC-1112/2012",
  "Causa penal": "CP-FIC-116/2012",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Golfo (ficticio)",
  "Pena en años": 20,
  "Fecha de sentencia": "2014-06-23",
  "Fecha de inicio": "2012-04-20",
  "Fecha de cumplimiento": "2032-04-20",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 18,
  "Nombre completo": "Edgar Villaseñor Montes",
  "Expediente": "EXP-FIC-1119/2019",
  "Causa penal": "CP-FIC-117/2019",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Regional Lago Azul (ficticio)",
  "Pena en años": 24,
  "Fecha de sentencia": "2021-09-06",
  "Fecha de inicio": "2019-09-17",
  "Fecha de cumplimiento": "2043-09-17",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 19,
  "Nombre completo": "Jesús Manuel Estrada Montes",
  "Expediente": "EXP-FIC-1126/2022",
  "Causa penal": "CP-FIC-118/2022",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noroeste (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2023-11-08",
  "Fecha de inicio": "2022-04-14",
  "Fecha de cumplimiento": "2030-04-14",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 20,
  "Nombre completo": "Adrián Sandoval Fuentes",
  "Expediente": "EXP-FIC-1133/2015",
  "Causa penal": "CP-FIC-119/2015",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Frontera (ficticio)",
  "Pena en años": 17,
  "Fecha de sentencia": "2016-10-02",
  "Fecha de inicio": "2015-11-19",
  "Fecha de cumplimiento": "2032-11-19",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 21,
  "Nombre completo": "José Luis Hernández Ruiz",
  "Expediente": "EXP-FIC-1140/2017",
  "Causa penal": "CP-FIC-120/2017",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Oriente (ficticio)",
  "Pena en años": 32,
  "Fecha de sentencia": "2018-09-16",
  "Fecha de inicio": "2017-10-20",
  "Fecha de cumplimiento": "2049-10-20",
  "Observaciones": "Homonimia ficticia de prueba: existe otro registro con el mismo nombre y distinta causa."
 },
 {
  "ID": 22,
  "Nombre completo": "Yolanda Castañeda Trejo",
  "Expediente": "EXP-FIC-1147/2012",
  "Causa penal": "CP-FIC-121/2012",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Estatal Valle Alto (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2015-02-07",
  "Fecha de inicio": "2012-11-12",
  "Fecha de cumplimiento": "2020-11-12",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 23,
  "Nombre completo": "Marco Antonio Escobar Lozano",
  "Expediente": "EXP-FIC-1154/2015",
  "Causa penal": "CP-FIC-122/2015",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Altos (ficticio)",
  "Pena en años": 12,
  "Fecha de sentencia": "2017-05-05",
  "Fecha de inicio": "2015-02-14",
  "Fecha de cumplimiento": "2027-02-14",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 24,
  "Nombre completo": "Daniela Castañeda Rangel",
  "Expediente": "EXP-FIC-1161/2017",
  "Causa penal": "CP-FIC-123/2017",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Sierra Madre (ficticio)",
  "Pena en años": 41,
  "Fecha de sentencia": "2019-02-03",
  "Fecha de inicio": "2017-05-10",
  "Fecha de cumplimiento": "2058-05-10",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 25,
  "Nombre completo": "Diego Solís Velasco",
  "Expediente": "EXP-FIC-1168/2016",
  "Causa penal": "CP-FIC-124/2016",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Estatal Costa Norte (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2018-06-22",
  "Fecha de inicio": "2016-01-10",
  "Fecha de cumplimiento": "2024-01-10",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 26,
  "Nombre completo": "Isaac Velasco Figueroa",
  "Expediente": "EXP-FIC-1175/2022",
  "Causa penal": "CP-FIC-125/2022",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Volcanes (ficticio)",
  "Pena en años": 17,
  "Fecha de sentencia": "2022-10-20",
  "Fecha de inicio": "2022-03-26",
  "Fecha de cumplimiento": "2039-03-26",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 27,
  "Nombre completo": "Carlos Iván Orozco Cárdenas",
  "Expediente": "EXP-FIC-1182/2013",
  "Causa penal": "CP-FIC-126/2013",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Golfo (ficticio)",
  "Pena en años": 40,
  "Fecha de sentencia": "2014-01-29",
  "Fecha de inicio": "2013-01-10",
  "Fecha de cumplimiento": "2053-01-10",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 28,
  "Nombre completo": "Hilda Valdez Trejo",
  "Expediente": "EXP-FIC-1189/2022",
  "Causa penal": "CP-FIC-127/2022",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Regional Lago Azul (ficticio)",
  "Pena en años": 7,
  "Fecha de sentencia": "2024-09-20",
  "Fecha de inicio": "2022-09-20",
  "Fecha de cumplimiento": "2029-09-20",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 29,
  "Nombre completo": "Araceli Rosales Garza",
  "Expediente": "EXP-FIC-1196/2022",
  "Causa penal": "CP-FIC-128/2022",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Pacífico (ficticio)",
  "Pena en años": 11,
  "Fecha de sentencia": "2023-05-20",
  "Fecha de inicio": "2022-09-12",
  "Fecha de cumplimiento": "2033-09-12",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 30,
  "Nombre completo": "Manuel Cervantes Rosales",
  "Expediente": "EXP-FIC-1203/2018",
  "Causa penal": "CP-FIC-129/2018",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Barrancas (ficticio)",
  "Pena en años": 35,
  "Fecha de sentencia": "2020-12-05",
  "Fecha de inicio": "2018-07-25",
  "Fecha de cumplimiento": "2053-07-25",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 31,
  "Nombre completo": "Rocío Lozano Figueroa",
  "Expediente": "EXP-FIC-1210/2022",
  "Causa penal": "CP-FIC-130/2022",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Oriente (ficticio)",
  "Pena en años": 3,
  "Fecha de sentencia": "2024-04-12",
  "Fecha de inicio": "2022-03-01",
  "Fecha de cumplimiento": "2025-03-01",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 32,
  "Nombre completo": "María Fernanda López Castro",
  "Expediente": "EXP-FIC-1217/2022",
  "Causa penal": "CP-FIC-131/2022",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Región Centro (ficticio)",
  "Pena en años": 12,
  "Fecha de sentencia": "2023-06-08",
  "Fecha de inicio": "2022-02-10",
  "Fecha de cumplimiento": "2034-02-10",
  "Observaciones": "Homonimia ficticia de prueba: existe otro registro con el mismo nombre y distinta causa."
 },
 {
  "ID": 33,
  "Nombre completo": "Rocío Cabrera Aguilar",
  "Expediente": "EXP-FIC-1224/2021",
  "Causa penal": "CP-FIC-132/2021",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Altos (ficticio)",
  "Pena en años": 27,
  "Fecha de sentencia": "2023-11-05",
  "Fecha de inicio": "2021-09-03",
  "Fecha de cumplimiento": "2048-09-03",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 34,
  "Nombre completo": "Ulises Zamora Benítez",
  "Expediente": "EXP-FIC-1231/2021",
  "Causa penal": "CP-FIC-133/2021",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Sierra Madre (ficticio)",
  "Pena en años": 7,
  "Fecha de sentencia": "2022-05-15",
  "Fecha de inicio": "2021-06-04",
  "Fecha de cumplimiento": "2028-06-04",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 35,
  "Nombre completo": "Jorge Alberto Navarro Salazar",
  "Expediente": "EXP-FIC-1238/2013",
  "Causa penal": "CP-FIC-134/2013",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Desierto (ficticio)",
  "Pena en años": 15,
  "Fecha de sentencia": "2014-01-19",
  "Fecha de inicio": "2013-04-06",
  "Fecha de cumplimiento": "2028-04-06",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 36,
  "Nombre completo": "Leonardo Figueroa Robles",
  "Expediente": "EXP-FIC-1245/2022",
  "Causa penal": "CP-FIC-135/2022",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Volcanes (ficticio)",
  "Pena en años": 42,
  "Fecha de sentencia": "2024-08-19",
  "Fecha de inicio": "2022-10-17",
  "Fecha de cumplimiento": "2064-10-17",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 37,
  "Nombre completo": "Cristian Barrios Ibarra",
  "Expediente": "EXP-FIC-1252/2017",
  "Causa penal": "CP-FIC-136/2017",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Sureste (ficticio)",
  "Pena en años": 5,
  "Fecha de sentencia": "2018-08-30",
  "Fecha de inicio": "2017-08-30",
  "Fecha de cumplimiento": "2022-08-28",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 38,
  "Nombre completo": "Rodrigo Cordero Garza",
  "Expediente": "EXP-FIC-1259/2020",
  "Causa penal": "CP-FIC-137/2020",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Regional Lago Azul (ficticio)",
  "Pena en años": 15,
  "Fecha de sentencia": "2023-01-30",
  "Fecha de inicio": "2020-10-30",
  "Fecha de cumplimiento": "2035-10-28",
  "Observaciones": "Sin observaciones adicionales."
 },
 {
  "ID": 39,
  "Nombre completo": "Beatriz Ochoa Navarro",
  "Expediente": "EXP-FIC-1266/2016",
  "Causa penal": "CP-FIC-138/2016",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noroeste (ficticio)",
  "Pena en años": 29,
  "Fecha de sentencia": "2018-04-17",
  "Fecha de inicio": "2016-06-02",
  "Fecha de cumplimiento": "2045-06-02",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 40,
  "Nombre completo": "Alma Delia Cervantes Valencia",
  "Expediente": "EXP-FIC-1273/2017",
  "Causa penal": "CP-FIC-139/2017",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Frontera (ficticio)",
  "Pena en años": 6,
  "Fecha de sentencia": "2020-01-08",
  "Fecha de inicio": "2017-08-27",
  "Fecha de cumplimiento": "2023-08-27",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 41,
  "Nombre completo": "Esteban Maldonado Camacho",
  "Expediente": "EXP-FIC-1280/2016",
  "Causa penal": "CP-FIC-140/2016",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Oriente (ficticio)",
  "Pena en años": 11,
  "Fecha de sentencia": "2018-05-28",
  "Fecha de inicio": "2016-10-09",
  "Fecha de cumplimiento": "2027-10-09",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 42,
  "Nombre completo": "Jesús Manuel Rangel Zavala",
  "Expediente": "EXP-FIC-1287/2012",
  "Causa penal": "CP-FIC-141/2012",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Región Centro (ficticio)",
  "Pena en años": 36,
  "Fecha de sentencia": "2013-07-23",
  "Fecha de inicio": "2012-05-19",
  "Fecha de cumplimiento": "2048-05-19",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 43,
  "Nombre completo": "Juan Pablo Ramírez Soto",
  "Expediente": "EXP-FIC-1294/2020",
  "Causa penal": "CP-FIC-142/2020",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Altos (ficticio)",
  "Pena en años": 5,
  "Fecha de sentencia": "2021-11-10",
  "Fecha de inicio": "2020-03-16",
  "Fecha de cumplimiento": "2025-03-16",
  "Observaciones": "Homonimia ficticia de prueba: existe otro registro con el mismo nombre y distinta causa."
 },
 {
  "ID": 44,
  "Nombre completo": "Cecilia Lozano Domínguez",
  "Expediente": "EXP-FIC-1301/2017",
  "Causa penal": "CP-FIC-143/2017",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Sierra Madre (ficticio)",
  "Pena en años": 15,
  "Fecha de sentencia": "2018-10-17",
  "Fecha de inicio": "2017-11-06",
  "Fecha de cumplimiento": "2032-11-06",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 45,
  "Nombre completo": "Karina Zamora Velasco",
  "Expediente": "EXP-FIC-1308/2014",
  "Causa penal": "CP-FIC-144/2014",
  "Delito": "Secuestro",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Desierto (ficticio)",
  "Pena en años": 28,
  "Fecha de sentencia": "2016-01-06",
  "Fecha de inicio": "2014-08-18",
  "Fecha de cumplimiento": "2042-08-18",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 46,
  "Nombre completo": "Karina Ochoa Rangel",
  "Expediente": "EXP-FIC-1315/2012",
  "Causa penal": "CP-FIC-145/2012",
  "Delito": "Secuestro",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Regional de Reinserción Sur (ficticio)",
  "Pena en años": 7,
  "Fecha de sentencia": "2013-12-29",
  "Fecha de inicio": "2012-10-26",
  "Fecha de cumplimiento": "2019-10-26",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 47,
  "Nombre completo": "Lorena Medina Sandoval",
  "Expediente": "EXP-FIC-1322/2013",
  "Causa penal": "CP-FIC-146/2013",
  "Delito": "Contra la salud (transporte)",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Sureste (ficticio)",
  "Pena en años": 12,
  "Fecha de sentencia": "2015-07-15",
  "Fecha de inicio": "2013-03-10",
  "Fecha de cumplimiento": "2025-03-10",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 48,
  "Nombre completo": "Samuel Zavala Galindo",
  "Expediente": "EXP-FIC-1329/2023",
  "Causa penal": "CP-FIC-147/2023",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Tierra Caliente (ficticio)",
  "Pena en años": 50,
  "Fecha de sentencia": "2025-03-25",
  "Fecha de inicio": "2023-01-20",
  "Fecha de cumplimiento": "2073-01-20",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 49,
  "Nombre completo": "Salvador Rosales Velasco",
  "Expediente": "EXP-FIC-1336/2012",
  "Causa penal": "CP-FIC-148/2012",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noroeste (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2013-09-18",
  "Fecha de inicio": "2012-09-04",
  "Fecha de cumplimiento": "2020-09-04",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 50,
  "Nombre completo": "Gloria Alvarado Campos",
  "Expediente": "EXP-FIC-1343/2021",
  "Causa penal": "CP-FIC-149/2021",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Frontera (ficticio)",
  "Pena en años": 12,
  "Fecha de sentencia": "2022-08-21",
  "Fecha de inicio": "2021-05-15",
  "Fecha de cumplimiento": "2033-05-15",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 51,
  "Nombre completo": "Jesús Manuel Leyva Alvarado",
  "Expediente": "EXP-FIC-1350/2016",
  "Causa penal": "CP-FIC-150/2016",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Oriente (ficticio)",
  "Pena en años": 43,
  "Fecha de sentencia": "2018-02-24",
  "Fecha de inicio": "2016-07-31",
  "Fecha de cumplimiento": "2059-07-28",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 52,
  "Nombre completo": "Luis Enrique Orozco Contreras",
  "Expediente": "EXP-FIC-1357/2021",
  "Causa penal": "CP-FIC-151/2021",
  "Delito": "Secuestro",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Estatal Valle Alto (ficticio)",
  "Pena en años": 3,
  "Fecha de sentencia": "2023-02-06",
  "Fecha de inicio": "2021-03-25",
  "Fecha de cumplimiento": "2024-03-25",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 53,
  "Nombre completo": "Emilio Benítez Trejo",
  "Expediente": "EXP-FIC-1364/2022",
  "Causa penal": "CP-FIC-152/2022",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Altos (ficticio)",
  "Pena en años": 15,
  "Fecha de sentencia": "2023-05-14",
  "Fecha de inicio": "2022-07-10",
  "Fecha de cumplimiento": "2037-07-10",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 54,
  "Nombre completo": "Adrián Galindo Aguilar",
  "Expediente": "EXP-FIC-1371/2016",
  "Causa penal": "CP-FIC-153/2016",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noreste (ficticio)",
  "Pena en años": 49,
  "Fecha de sentencia": "2017-05-27",
  "Fecha de inicio": "2016-02-18",
  "Fecha de cumplimiento": "2065-02-18",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 55,
  "Nombre completo": "Blanca Estela Villaseñor Contreras",
  "Expediente": "EXP-FIC-1378/2020",
  "Causa penal": "CP-FIC-154/2020",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Desierto (ficticio)",
  "Pena en años": 4,
  "Fecha de sentencia": "2023-05-02",
  "Fecha de inicio": "2020-11-14",
  "Fecha de cumplimiento": "2024-11-14",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 56,
  "Nombre completo": "María Fernanda Garza Contreras",
  "Expediente": "EXP-FIC-1385/2022",
  "Causa penal": "CP-FIC-155/2022",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Volcanes (ficticio)",
  "Pena en años": 18,
  "Fecha de sentencia": "2024-08-21",
  "Fecha de inicio": "2022-05-16",
  "Fecha de cumplimiento": "2040-05-16",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 57,
  "Nombre completo": "Diego Aguilar Montes",
  "Expediente": "EXP-FIC-1392/2013",
  "Causa penal": "CP-FIC-156/2013",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Sureste (ficticio)",
  "Pena en años": 43,
  "Fecha de sentencia": "2015-05-04",
  "Fecha de inicio": "2013-09-18",
  "Fecha de cumplimiento": "2056-09-18",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 58,
  "Nombre completo": "Gabriel Valencia Camacho",
  "Expediente": "EXP-FIC-1399/2021",
  "Causa penal": "CP-FIC-157/2021",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Regional Lago Azul (ficticio)",
  "Pena en años": 5,
  "Fecha de sentencia": "2022-05-17",
  "Fecha de inicio": "2021-01-06",
  "Fecha de cumplimiento": "2026-01-06",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 59,
  "Nombre completo": "Julián Benítez Navarro",
  "Expediente": "EXP-FIC-1406/2017",
  "Causa penal": "CP-FIC-158/2017",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noroeste (ficticio)",
  "Pena en años": 19,
  "Fecha de sentencia": "2018-06-08",
  "Fecha de inicio": "2017-05-06",
  "Fecha de cumplimiento": "2036-05-06",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 60,
  "Nombre completo": "Isaac Contreras Medina",
  "Expediente": "EXP-FIC-1413/2023",
  "Causa penal": "CP-FIC-159/2023",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Barrancas (ficticio)",
  "Pena en años": 44,
  "Fecha de sentencia": "2025-11-01",
  "Fecha de inicio": "2023-05-23",
  "Fecha de cumplimiento": "2067-05-23",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 61,
  "Nombre completo": "Isaac Palacios Maldonado",
  "Expediente": "EXP-FIC-1420/2020",
  "Causa penal": "CP-FIC-160/2020",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Oriente (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2022-01-21",
  "Fecha de inicio": "2020-02-26",
  "Fecha de cumplimiento": "2028-02-26",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 62,
  "Nombre completo": "Luis Enrique Quintero Arellano",
  "Expediente": "EXP-FIC-1427/2015",
  "Causa penal": "CP-FIC-161/2015",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Región Centro (ficticio)",
  "Pena en años": 15,
  "Fecha de sentencia": "2017-08-04",
  "Fecha de inicio": "2015-05-14",
  "Fecha de cumplimiento": "2030-05-14",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 63,
  "Nombre completo": "Ángel Aguilar Peña",
  "Expediente": "EXP-FIC-1434/2015",
  "Causa penal": "CP-FIC-162/2015",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Altos (ficticio)",
  "Pena en años": 47,
  "Fecha de sentencia": "2015-08-22",
  "Fecha de inicio": "2015-01-30",
  "Fecha de cumplimiento": "2062-01-28",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 64,
  "Nombre completo": "Lorena Pacheco Zavala",
  "Expediente": "EXP-FIC-1441/2018",
  "Causa penal": "CP-FIC-163/2018",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Sierra Madre (ficticio)",
  "Pena en años": 2,
  "Fecha de sentencia": "2019-12-07",
  "Fecha de inicio": "2018-09-07",
  "Fecha de cumplimiento": "2020-09-07",
  "Observaciones": "Sin observaciones adicionales."
 },
 {
  "ID": 65,
  "Nombre completo": "Noemí Espinoza Estrada",
  "Expediente": "EXP-FIC-1448/2013",
  "Causa penal": "CP-FIC-164/2013",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Desierto (ficticio)",
  "Pena en años": 15,
  "Fecha de sentencia": "2014-03-29",
  "Fecha de inicio": "2013-02-07",
  "Fecha de cumplimiento": "2028-02-07",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 66,
  "Nombre completo": "Bruno Bautista Salazar",
  "Expediente": "EXP-FIC-1455/2019",
  "Causa penal": "CP-FIC-165/2019",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Regional de Reinserción Sur (ficticio)",
  "Pena en años": 21,
  "Fecha de sentencia": "2021-12-05",
  "Fecha de inicio": "2019-11-02",
  "Fecha de cumplimiento": "2040-11-02",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 67,
  "Nombre completo": "Valeria Leyva Miranda",
  "Expediente": "EXP-FIC-1462/2018",
  "Causa penal": "CP-FIC-166/2018",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Golfo (ficticio)",
  "Pena en años": 9,
  "Fecha de sentencia": "2020-06-09",
  "Fecha de inicio": "2018-02-22",
  "Fecha de cumplimiento": "2027-02-22",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 68,
  "Nombre completo": "José Luis Hernández Ruiz",
  "Expediente": "EXP-FIC-1469/2017",
  "Causa penal": "CP-FIC-167/2017",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Tierra Caliente (ficticio)",
  "Pena en años": 11,
  "Fecha de sentencia": "2018-11-26",
  "Fecha de inicio": "2017-04-22",
  "Fecha de cumplimiento": "2028-04-22",
  "Observaciones": "Homonimia ficticia de prueba: existe otro registro con el mismo nombre y distinta causa."
 },
 {
  "ID": 69,
  "Nombre completo": "María Fernanda Ochoa Robles",
  "Expediente": "EXP-FIC-1476/2015",
  "Causa penal": "CP-FIC-168/2015",
  "Delito": "Secuestro",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Pacífico (ficticio)",
  "Pena en años": 30,
  "Fecha de sentencia": "2018-03-18",
  "Fecha de inicio": "2015-10-19",
  "Fecha de cumplimiento": "2045-10-19",
  "Observaciones": "Sin observaciones adicionales."
 },
 {
  "ID": 70,
  "Nombre completo": "Pablo Cervantes Cabrera",
  "Expediente": "EXP-FIC-1483/2021",
  "Causa penal": "CP-FIC-169/2021",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Frontera (ficticio)",
  "Pena en años": 7,
  "Fecha de sentencia": "2022-06-14",
  "Fecha de inicio": "2021-08-19",
  "Fecha de cumplimiento": "2028-08-19",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 71,
  "Nombre completo": "Ramiro Mejía Miranda",
  "Expediente": "EXP-FIC-1490/2022",
  "Causa penal": "CP-FIC-170/2022",
  "Delito": "Contra la salud (transporte)",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Norte (ficticio)",
  "Pena en años": 15,
  "Fecha de sentencia": "2024-02-12",
  "Fecha de inicio": "2022-06-22",
  "Fecha de cumplimiento": "2037-06-22",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 72,
  "Nombre completo": "Elena Solís Tapia",
  "Expediente": "EXP-FIC-1497/2021",
  "Causa penal": "CP-FIC-171/2021",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Región Centro (ficticio)",
  "Pena en años": 36,
  "Fecha de sentencia": "2023-12-29",
  "Fecha de inicio": "2021-09-02",
  "Fecha de cumplimiento": "2057-09-02",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 73,
  "Nombre completo": "Mario Palacios Galindo",
  "Expediente": "EXP-FIC-1504/2023",
  "Causa penal": "CP-FIC-172/2023",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Occidente (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2025-08-01",
  "Fecha de inicio": "2023-08-24",
  "Fecha de cumplimiento": "2031-08-24",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 74,
  "Nombre completo": "Emilio Tapia Zavala",
  "Expediente": "EXP-FIC-1511/2017",
  "Causa penal": "CP-FIC-173/2017",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Sierra Madre (ficticio)",
  "Pena en años": 11,
  "Fecha de sentencia": "2019-06-05",
  "Fecha de inicio": "2017-02-17",
  "Fecha de cumplimiento": "2028-02-17",
  "Observaciones": "Sin observaciones adicionales."
 },
 {
  "ID": 75,
  "Nombre completo": "Patricia Cabrera Camacho",
  "Expediente": "EXP-FIC-1518/2017",
  "Causa penal": "CP-FIC-174/2017",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Estatal Costa Norte (ficticio)",
  "Pena en años": 41,
  "Fecha de sentencia": "2019-01-18",
  "Fecha de inicio": "2017-10-27",
  "Fecha de cumplimiento": "2058-10-27",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 76,
  "Nombre completo": "Beatriz Márquez Navarro",
  "Expediente": "EXP-FIC-1525/2022",
  "Causa penal": "CP-FIC-175/2022",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Volcanes (ficticio)",
  "Pena en años": 7,
  "Fecha de sentencia": "2023-08-15",
  "Fecha de inicio": "2022-07-23",
  "Fecha de cumplimiento": "2029-07-23",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 77,
  "Nombre completo": "César Figueroa Márquez",
  "Expediente": "EXP-FIC-1532/2023",
  "Causa penal": "CP-FIC-176/2023",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Sureste (ficticio)",
  "Pena en años": 16,
  "Fecha de sentencia": "2026-01-27",
  "Fecha de inicio": "2023-10-18",
  "Fecha de cumplimiento": "2039-10-18",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 78,
  "Nombre completo": "Emilio Aguilar Escobar",
  "Expediente": "EXP-FIC-1539/2017",
  "Causa penal": "CP-FIC-177/2017",
  "Delito": "Contra la salud (transporte)",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Regional Lago Azul (ficticio)",
  "Pena en años": 33,
  "Fecha de sentencia": "2018-08-30",
  "Fecha de inicio": "2017-04-16",
  "Fecha de cumplimiento": "2050-04-16",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 79,
  "Nombre completo": "María Fernanda López Castro",
  "Expediente": "EXP-FIC-1546/2021",
  "Causa penal": "CP-FIC-178/2021",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noroeste (ficticio)",
  "Pena en años": 2,
  "Fecha de sentencia": "2022-06-19",
  "Fecha de inicio": "2021-02-12",
  "Fecha de cumplimiento": "2023-02-12",
  "Observaciones": "Homonimia ficticia de prueba: existe otro registro con el mismo nombre y distinta causa."
 },
 {
  "ID": 80,
  "Nombre completo": "César Castañeda Cabrera",
  "Expediente": "EXP-FIC-1553/2017",
  "Causa penal": "CP-FIC-179/2017",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Barrancas (ficticio)",
  "Pena en años": 19,
  "Fecha de sentencia": "2019-05-15",
  "Fecha de inicio": "2017-08-02",
  "Fecha de cumplimiento": "2036-08-02",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 81,
  "Nombre completo": "Omar Lara Espinoza",
  "Expediente": "EXP-FIC-1560/2023",
  "Causa penal": "CP-FIC-180/2023",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Oriente (ficticio)",
  "Pena en años": 40,
  "Fecha de sentencia": "2026-01-05",
  "Fecha de inicio": "2023-11-07",
  "Fecha de cumplimiento": "2063-11-07",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 82,
  "Nombre completo": "Hilda Arellano Cervantes",
  "Expediente": "EXP-FIC-1567/2023",
  "Causa penal": "CP-FIC-181/2023",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Región Centro (ficticio)",
  "Pena en años": 6,
  "Fecha de sentencia": "2023-11-24",
  "Fecha de inicio": "2023-02-28",
  "Fecha de cumplimiento": "2029-02-28",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 83,
  "Nombre completo": "Raúl Ochoa Miranda",
  "Expediente": "EXP-FIC-1574/2023",
  "Causa penal": "CP-FIC-182/2023",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Occidente (ficticio)",
  "Pena en años": 11,
  "Fecha de sentencia": "2023-10-26",
  "Fecha de inicio": "2023-01-30",
  "Fecha de cumplimiento": "2034-01-28",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 84,
  "Nombre completo": "Araceli Alvarado Garza",
  "Expediente": "EXP-FIC-1581/2020",
  "Causa penal": "CP-FIC-183/2020",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noreste (ficticio)",
  "Pena en años": 37,
  "Fecha de sentencia": "2021-06-02",
  "Fecha de inicio": "2020-10-12",
  "Fecha de cumplimiento": "2057-10-12",
  "Observaciones": "Promovió juicio de amparo directo (dato ficticio)."
 },
 {
  "ID": 85,
  "Nombre completo": "Karina Barrios Villaseñor",
  "Expediente": "EXP-FIC-1588/2018",
  "Causa penal": "CP-FIC-184/2018",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Estatal Costa Norte (ficticio)",
  "Pena en años": 9,
  "Fecha de sentencia": "2018-12-14",
  "Fecha de inicio": "2018-05-03",
  "Fecha de cumplimiento": "2027-05-03",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 86,
  "Nombre completo": "Alma Delia Palacios Miranda",
  "Expediente": "EXP-FIC-1595/2012",
  "Causa penal": "CP-FIC-185/2012",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Regional de Reinserción Sur (ficticio)",
  "Pena en años": 10,
  "Fecha de sentencia": "2014-06-08",
  "Fecha de inicio": "2012-08-18",
  "Fecha de cumplimiento": "2022-08-18",
  "Observaciones": "Sin observaciones adicionales."
 },
 {
  "ID": 87,
  "Nombre completo": "Cristian Arellano Palacios",
  "Expediente": "EXP-FIC-1602/2016",
  "Causa penal": "CP-FIC-186/2016",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Sureste (ficticio)",
  "Pena en años": 37,
  "Fecha de sentencia": "2018-07-20",
  "Fecha de inicio": "2016-03-18",
  "Fecha de cumplimiento": "2053-03-18",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 88,
  "Nombre completo": "César Medina Lara",
  "Expediente": "EXP-FIC-1609/2018",
  "Causa penal": "CP-FIC-187/2018",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Regional Lago Azul (ficticio)",
  "Pena en años": 3,
  "Fecha de sentencia": "2020-05-14",
  "Fecha de inicio": "2018-07-23",
  "Fecha de cumplimiento": "2021-07-23",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 89,
  "Nombre completo": "Víctor Hugo Lozano Salazar",
  "Expediente": "EXP-FIC-1616/2017",
  "Causa penal": "CP-FIC-188/2017",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noroeste (ficticio)",
  "Pena en años": 11,
  "Fecha de sentencia": "2017-12-08",
  "Fecha de inicio": "2017-03-21",
  "Fecha de cumplimiento": "2028-03-21",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 90,
  "Nombre completo": "Juan Pablo Ramírez Soto",
  "Expediente": "EXP-FIC-1623/2012",
  "Causa penal": "CP-FIC-189/2012",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Barrancas (ficticio)",
  "Pena en años": 28,
  "Fecha de sentencia": "2013-11-24",
  "Fecha de inicio": "2012-03-10",
  "Fecha de cumplimiento": "2040-03-10",
  "Observaciones": "Homonimia ficticia de prueba: existe otro registro con el mismo nombre y distinta causa."
 },
 {
  "ID": 91,
  "Nombre completo": "Javier Aguilar Figueroa",
  "Expediente": "EXP-FIC-1630/2020",
  "Causa penal": "CP-FIC-190/2020",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Oriente (ficticio)",
  "Pena en años": 7,
  "Fecha de sentencia": "2022-05-21",
  "Fecha de inicio": "2020-10-01",
  "Fecha de cumplimiento": "2027-10-01",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 92,
  "Nombre completo": "Raúl Valdez Delgado",
  "Expediente": "EXP-FIC-1637/2019",
  "Causa penal": "CP-FIC-191/2019",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Región Centro (ficticio)",
  "Pena en años": 14,
  "Fecha de sentencia": "2020-08-02",
  "Fecha de inicio": "2019-10-26",
  "Fecha de cumplimiento": "2033-10-26",
  "Observaciones": "Sin observaciones adicionales."
 },
 {
  "ID": 93,
  "Nombre completo": "Valeria Cárdenas Miranda",
  "Expediente": "EXP-FIC-1644/2015",
  "Causa penal": "CP-FIC-192/2015",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Altos (ficticio)",
  "Pena en años": 40,
  "Fecha de sentencia": "2016-08-24",
  "Fecha de inicio": "2015-02-05",
  "Fecha de cumplimiento": "2055-02-05",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 94,
  "Nombre completo": "Marco Antonio Cárdenas Pacheco",
  "Expediente": "EXP-FIC-1651/2018",
  "Causa penal": "CP-FIC-193/2018",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noreste (ficticio)",
  "Pena en años": 7,
  "Fecha de sentencia": "2020-06-11",
  "Fecha de inicio": "2018-08-07",
  "Fecha de cumplimiento": "2025-08-07",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 95,
  "Nombre completo": "Arturo Rosales Márquez",
  "Expediente": "EXP-FIC-1658/2023",
  "Causa penal": "CP-FIC-194/2023",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Desierto (ficticio)",
  "Pena en años": 16,
  "Fecha de sentencia": "2024-07-28",
  "Fecha de inicio": "2023-03-18",
  "Fecha de cumplimiento": "2039-03-18",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 96,
  "Nombre completo": "José Luis Hernández Ríos",
  "Expediente": "EXP-FIC-1665/2012",
  "Causa penal": "CP-FIC-195/2012",
  "Delito": "Secuestro",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Regional de Reinserción Sur (ficticio)",
  "Pena en años": 47,
  "Fecha de sentencia": "2013-08-08",
  "Fecha de inicio": "2012-11-15",
  "Fecha de cumplimiento": "2059-11-15",
  "Observaciones": "Nombre ficticio similar a otro registro, para probar búsquedas ambiguas."
 },
 {
  "ID": 97,
  "Nombre completo": "Sergio Valencia Contreras",
  "Expediente": "EXP-FIC-1672/2014",
  "Causa penal": "CP-FIC-196/2014",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Golfo (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2016-06-25",
  "Fecha de inicio": "2014-03-28",
  "Fecha de cumplimiento": "2022-03-28",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 98,
  "Nombre completo": "Sergio Velasco Camacho",
  "Expediente": "EXP-FIC-1679/2016",
  "Causa penal": "CP-FIC-197/2016",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Regional Lago Azul (ficticio)",
  "Pena en años": 17,
  "Fecha de sentencia": "2018-08-02",
  "Fecha de inicio": "2016-09-23",
  "Fecha de cumplimiento": "2033-09-23",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 99,
  "Nombre completo": "Víctor Hugo Camacho Cárdenas",
  "Expediente": "EXP-FIC-1686/2018",
  "Causa penal": "CP-FIC-198/2018",
  "Delito": "Contra la salud (transporte)",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noroeste (ficticio)",
  "Pena en años": 49,
  "Fecha de sentencia": "2020-03-03",
  "Fecha de inicio": "2018-04-12",
  "Fecha de cumplimiento": "2067-04-12",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 100,
  "Nombre completo": "Ricardo Cárdenas Sandoval",
  "Expediente": "EXP-FIC-1693/2015",
  "Causa penal": "CP-FIC-199/2015",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Frontera (ficticio)",
  "Pena en años": 6,
  "Fecha de sentencia": "2017-08-04",
  "Fecha de inicio": "2015-11-12",
  "Fecha de cumplimiento": "2021-11-12",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 101,
  "Nombre completo": "Benito Valdez Cabrera",
  "Expediente": "EXP-FIC-1700/2016",
  "Causa penal": "CP-FIC-200/2016",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Oriente (ficticio)",
  "Pena en años": 19,
  "Fecha de sentencia": "2017-11-07",
  "Fecha de inicio": "2016-08-18",
  "Fecha de cumplimiento": "2035-08-18",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 102,
  "Nombre completo": "Bruno Barrios Rosales",
  "Expediente": "EXP-FIC-1707/2016",
  "Causa penal": "CP-FIC-201/2016",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Estatal Valle Alto (ficticio)",
  "Pena en años": 39,
  "Fecha de sentencia": "2018-10-04",
  "Fecha de inicio": "2016-07-27",
  "Fecha de cumplimiento": "2055-07-27",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 103,
  "Nombre completo": "Isaac Villaseñor Cárdenas",
  "Expediente": "EXP-FIC-1714/2012",
  "Causa penal": "CP-FIC-202/2012",
  "Delito": "Contra la salud (transporte)",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Altos (ficticio)",
  "Pena en años": 6,
  "Fecha de sentencia": "2014-07-02",
  "Fecha de inicio": "2012-10-26",
  "Fecha de cumplimiento": "2018-10-26",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 104,
  "Nombre completo": "Néstor Villaseñor Garza",
  "Expediente": "EXP-FIC-1721/2019",
  "Causa penal": "CP-FIC-203/2019",
  "Delito": "Secuestro",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noreste (ficticio)",
  "Pena en años": 11,
  "Fecha de sentencia": "2021-06-15",
  "Fecha de inicio": "2019-06-26",
  "Fecha de cumplimiento": "2030-06-26",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 105,
  "Nombre completo": "José Luis Fernández Ruiz",
  "Expediente": "EXP-FIC-1728/2016",
  "Causa penal": "CP-FIC-204/2016",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Desierto (ficticio)",
  "Pena en años": 21,
  "Fecha de sentencia": "2017-02-05",
  "Fecha de inicio": "2016-07-09",
  "Fecha de cumplimiento": "2037-07-09",
  "Observaciones": "Nombre ficticio similar a otro registro, para probar búsquedas ambiguas."
 },
 {
  "ID": 106,
  "Nombre completo": "Tomás Delgado Sandoval",
  "Expediente": "EXP-FIC-1735/2012",
  "Causa penal": "CP-FIC-205/2012",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Regional de Reinserción Sur (ficticio)",
  "Pena en años": 6,
  "Fecha de sentencia": "2015-01-08",
  "Fecha de inicio": "2012-08-15",
  "Fecha de cumplimiento": "2018-08-15",
  "Observaciones": "Sin observaciones adicionales."
 },
 {
  "ID": 107,
  "Nombre completo": "Blanca Estela Gallardo Quintero",
  "Expediente": "EXP-FIC-1742/2020",
  "Causa penal": "CP-FIC-206/2020",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Sureste (ficticio)",
  "Pena en años": 18,
  "Fecha de sentencia": "2022-08-11",
  "Fecha de inicio": "2020-09-12",
  "Fecha de cumplimiento": "2038-09-12",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 108,
  "Nombre completo": "Gustavo Cervantes Lara",
  "Expediente": "EXP-FIC-1749/2018",
  "Causa penal": "CP-FIC-207/2018",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Tierra Caliente (ficticio)",
  "Pena en años": 48,
  "Fecha de sentencia": "2020-02-19",
  "Fecha de inicio": "2018-04-25",
  "Fecha de cumplimiento": "2066-04-25",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 109,
  "Nombre completo": "Gloria Ibarra Figueroa",
  "Expediente": "EXP-FIC-1756/2021",
  "Causa penal": "CP-FIC-208/2021",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Pacífico (ficticio)",
  "Pena en años": 6,
  "Fecha de sentencia": "2023-03-25",
  "Fecha de inicio": "2021-04-26",
  "Fecha de cumplimiento": "2027-04-26",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 110,
  "Nombre completo": "Ricardo Mejía Valencia",
  "Expediente": "EXP-FIC-1763/2012",
  "Causa penal": "CP-FIC-209/2012",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Barrancas (ficticio)",
  "Pena en años": 11,
  "Fecha de sentencia": "2013-11-26",
  "Fecha de inicio": "2012-07-03",
  "Fecha de cumplimiento": "2023-07-03",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 111,
  "Nombre completo": "Cecilia Miranda Cárdenas",
  "Expediente": "EXP-FIC-1770/2018",
  "Causa penal": "CP-FIC-210/2018",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Oriente (ficticio)",
  "Pena en años": 37,
  "Fecha de sentencia": "2020-07-13",
  "Fecha de inicio": "2018-10-01",
  "Fecha de cumplimiento": "2055-10-01",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 112,
  "Nombre completo": "Karina Mejía Maldonado",
  "Expediente": "EXP-FIC-1777/2020",
  "Causa penal": "CP-FIC-211/2020",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Estatal Valle Alto (ficticio)",
  "Pena en años": 9,
  "Fecha de sentencia": "2020-08-01",
  "Fecha de inicio": "2020-01-07",
  "Fecha de cumplimiento": "2029-01-07",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 113,
  "Nombre completo": "Pablo Zavala Palacios",
  "Expediente": "EXP-FIC-1784/2018",
  "Causa penal": "CP-FIC-212/2018",
  "Delito": "Operaciones con recursos de procedencia ilícita",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Altos (ficticio)",
  "Pena en años": 18,
  "Fecha de sentencia": "2020-01-16",
  "Fecha de inicio": "2018-04-24",
  "Fecha de cumplimiento": "2036-04-24",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 114,
  "Nombre completo": "María Fernanda López Castillo",
  "Expediente": "EXP-FIC-1791/2015",
  "Causa penal": "CP-FIC-213/2015",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noreste (ficticio)",
  "Pena en años": 30,
  "Fecha de sentencia": "2015-12-21",
  "Fecha de inicio": "2015-04-02",
  "Fecha de cumplimiento": "2045-04-02",
  "Observaciones": "Nombre ficticio similar a otro registro, para probar búsquedas ambiguas."
 },
 {
  "ID": 115,
  "Nombre completo": "Noemí Figueroa Garza",
  "Expediente": "EXP-FIC-1798/2014",
  "Causa penal": "CP-FIC-214/2014",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Estatal Costa Norte (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2015-01-22",
  "Fecha de inicio": "2014-04-06",
  "Fecha de cumplimiento": "2022-04-06",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 116,
  "Nombre completo": "Octavio Espinoza Barrios",
  "Expediente": "EXP-FIC-1805/2013",
  "Causa penal": "CP-FIC-215/2013",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Volcanes (ficticio)",
  "Pena en años": 20,
  "Fecha de sentencia": "2014-10-27",
  "Fecha de inicio": "2013-09-23",
  "Fecha de cumplimiento": "2033-09-23",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 117,
  "Nombre completo": "Gabriel Cordero Fuentes",
  "Expediente": "EXP-FIC-1812/2023",
  "Causa penal": "CP-FIC-216/2023",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Golfo (ficticio)",
  "Pena en años": 50,
  "Fecha de sentencia": "2024-11-03",
  "Fecha de inicio": "2023-10-30",
  "Fecha de cumplimiento": "2073-10-28",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 118,
  "Nombre completo": "Elena Benítez Guerrero",
  "Expediente": "EXP-FIC-1819/2022",
  "Causa penal": "CP-FIC-217/2022",
  "Delito": "Secuestro",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Regional Lago Azul (ficticio)",
  "Pena en años": 5,
  "Fecha de sentencia": "2023-09-08",
  "Fecha de inicio": "2022-10-10",
  "Fecha de cumplimiento": "2027-10-10",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 119,
  "Nombre completo": "Elena Figueroa Zamora",
  "Expediente": "EXP-FIC-1826/2021",
  "Causa penal": "CP-FIC-218/2021",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Pacífico (ficticio)",
  "Pena en años": 14,
  "Fecha de sentencia": "2022-04-28",
  "Fecha de inicio": "2021-08-15",
  "Fecha de cumplimiento": "2035-08-15",
  "Observaciones": "Pendiente de actualizar cómputo de la pena (dato ficticio)."
 },
 {
  "ID": 120,
  "Nombre completo": "Alma Delia Zavala Maldonado",
  "Expediente": "EXP-FIC-1833/2013",
  "Causa penal": "CP-FIC-219/2013",
  "Delito": "Robo de hidrocarburos",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Frontera (ficticio)",
  "Pena en años": 50,
  "Fecha de sentencia": "2014-10-16",
  "Fecha de inicio": "2013-01-18",
  "Fecha de cumplimiento": "2063-01-18",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 121,
  "Nombre completo": "Néstor Sandoval Trejo",
  "Expediente": "EXP-FIC-1840/2015",
  "Causa penal": "CP-FIC-220/2015",
  "Delito": "Secuestro",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Norte (ficticio)",
  "Pena en años": 7,
  "Fecha de sentencia": "2017-07-27",
  "Fecha de inicio": "2015-09-25",
  "Fecha de cumplimiento": "2022-09-25",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 122,
  "Nombre completo": "Beatriz Camacho Orozco",
  "Expediente": "EXP-FIC-1847/2021",
  "Causa penal": "CP-FIC-221/2021",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Estatal Valle Alto (ficticio)",
  "Pena en años": 13,
  "Fecha de sentencia": "2022-11-25",
  "Fecha de inicio": "2021-10-02",
  "Fecha de cumplimiento": "2034-10-02",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 123,
  "Nombre completo": "Alfonso Orozco Tapia",
  "Expediente": "EXP-FIC-1854/2018",
  "Causa penal": "CP-FIC-222/2018",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Altos (ficticio)",
  "Pena en años": 21,
  "Fecha de sentencia": "2019-10-23",
  "Fecha de inicio": "2018-11-08",
  "Fecha de cumplimiento": "2039-11-08",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 124,
  "Nombre completo": "Sergio Cabrera Aguilar",
  "Expediente": "EXP-FIC-1861/2020",
  "Causa penal": "CP-FIC-223/2020",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noreste (ficticio)",
  "Pena en años": 2,
  "Fecha de sentencia": "2020-11-02",
  "Fecha de inicio": "2020-03-16",
  "Fecha de cumplimiento": "2022-03-16",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 125,
  "Nombre completo": "Edgar Cárdenas Domínguez",
  "Expediente": "EXP-FIC-1868/2012",
  "Causa penal": "CP-FIC-224/2012",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Estatal Costa Norte (ficticio)",
  "Pena en años": 19,
  "Fecha de sentencia": "2013-08-23",
  "Fecha de inicio": "2012-04-09",
  "Fecha de cumplimiento": "2031-04-09",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 126,
  "Nombre completo": "Juan Pablo Pacheco Arellano",
  "Expediente": "EXP-FIC-1875/2019",
  "Causa penal": "CP-FIC-225/2019",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Regional de Reinserción Sur (ficticio)",
  "Pena en años": 31,
  "Fecha de sentencia": "2020-12-01",
  "Fecha de inicio": "2019-01-23",
  "Fecha de cumplimiento": "2050-01-23",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 127,
  "Nombre completo": "Octavio Barrios Solís",
  "Expediente": "EXP-FIC-1882/2013",
  "Causa penal": "CP-FIC-226/2013",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Golfo (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2014-05-14",
  "Fecha de inicio": "2013-05-20",
  "Fecha de cumplimiento": "2021-05-20",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 128,
  "Nombre completo": "Luis Enrique Aguilar Villaseñor",
  "Expediente": "EXP-FIC-1889/2019",
  "Causa penal": "CP-FIC-227/2019",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Regional Lago Azul (ficticio)",
  "Pena en años": 10,
  "Fecha de sentencia": "2020-07-16",
  "Fecha de inicio": "2019-07-22",
  "Fecha de cumplimiento": "2029-07-22",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 129,
  "Nombre completo": "Hugo Valdez Galindo",
  "Expediente": "EXP-FIC-1896/2013",
  "Causa penal": "CP-FIC-228/2013",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noroeste (ficticio)",
  "Pena en años": 41,
  "Fecha de sentencia": "2015-05-02",
  "Fecha de inicio": "2013-03-08",
  "Fecha de cumplimiento": "2054-03-08",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 130,
  "Nombre completo": "Ángel Salazar Figueroa",
  "Expediente": "EXP-FIC-1903/2013",
  "Causa penal": "CP-FIC-229/2013",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Barrancas (ficticio)",
  "Pena en años": 9,
  "Fecha de sentencia": "2014-06-24",
  "Fecha de inicio": "2013-09-24",
  "Fecha de cumplimiento": "2022-09-24",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 131,
  "Nombre completo": "Ricardo Rangel Contreras",
  "Expediente": "EXP-FIC-1910/2012",
  "Causa penal": "CP-FIC-230/2012",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Norte (ficticio)",
  "Pena en años": 10,
  "Fecha de sentencia": "2014-05-25",
  "Fecha de inicio": "2012-03-25",
  "Fecha de cumplimiento": "2022-03-25",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 132,
  "Nombre completo": "Héctor Espinoza Lozano",
  "Expediente": "EXP-FIC-1917/2023",
  "Causa penal": "CP-FIC-231/2023",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Región Centro (ficticio)",
  "Pena en años": 42,
  "Fecha de sentencia": "2024-10-22",
  "Fecha de inicio": "2023-05-27",
  "Fecha de cumplimiento": "2065-05-27",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 133,
  "Nombre completo": "Hugo Castañeda Valencia",
  "Expediente": "EXP-FIC-1924/2021",
  "Causa penal": "CP-FIC-232/2021",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Altos (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2022-10-04",
  "Fecha de inicio": "2021-08-21",
  "Fecha de cumplimiento": "2029-08-21",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 134,
  "Nombre completo": "Esteban Ochoa Castañeda",
  "Expediente": "EXP-FIC-1931/2018",
  "Causa penal": "CP-FIC-233/2018",
  "Delito": "Defraudación fiscal",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Sierra Madre (ficticio)",
  "Pena en años": 13,
  "Fecha de sentencia": "2020-07-15",
  "Fecha de inicio": "2018-11-19",
  "Fecha de cumplimiento": "2031-11-19",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 135,
  "Nombre completo": "Fabiola Cárdenas Arellano",
  "Expediente": "EXP-FIC-1938/2016",
  "Causa penal": "CP-FIC-234/2016",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Estatal Costa Norte (ficticio)",
  "Pena en años": 26,
  "Fecha de sentencia": "2017-06-08",
  "Fecha de inicio": "2016-09-17",
  "Fecha de cumplimiento": "2042-09-17",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 136,
  "Nombre completo": "Arturo Salazar Zavala",
  "Expediente": "EXP-FIC-1945/2012",
  "Causa penal": "CP-FIC-235/2012",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Volcanes (ficticio)",
  "Pena en años": 8,
  "Fecha de sentencia": "2014-05-09",
  "Fecha de inicio": "2012-02-26",
  "Fecha de cumplimiento": "2020-02-26",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 137,
  "Nombre completo": "Samuel Sandoval Guerrero",
  "Expediente": "EXP-FIC-1952/2021",
  "Causa penal": "CP-FIC-236/2021",
  "Delito": "Delitos contra el ambiente",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Golfo (ficticio)",
  "Pena en años": 13,
  "Fecha de sentencia": "2022-06-05",
  "Fecha de inicio": "2021-01-22",
  "Fecha de cumplimiento": "2034-01-22",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 138,
  "Nombre completo": "Marco Antonio Salazar Figueroa",
  "Expediente": "EXP-FIC-1959/2016",
  "Causa penal": "CP-FIC-237/2016",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Tierra Caliente (ficticio)",
  "Pena en años": 40,
  "Fecha de sentencia": "2018-10-24",
  "Fecha de inicio": "2016-09-29",
  "Fecha de cumplimiento": "2056-09-28",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 139,
  "Nombre completo": "María Fernanda Espinoza Barrios",
  "Expediente": "EXP-FIC-1966/2023",
  "Causa penal": "CP-FIC-238/2023",
  "Delito": "Contra la salud (posesión con fines de comercio)",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noroeste (ficticio)",
  "Pena en años": 5,
  "Fecha de sentencia": "2024-08-03",
  "Fecha de inicio": "2023-05-23",
  "Fecha de cumplimiento": "2028-05-23",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 140,
  "Nombre completo": "Cristian Bautista Delgado",
  "Expediente": "EXP-FIC-1973/2015",
  "Causa penal": "CP-FIC-239/2015",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Segundo de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Frontera (ficticio)",
  "Pena en años": 19,
  "Fecha de sentencia": "2017-03-12",
  "Fecha de inicio": "2015-01-27",
  "Fecha de cumplimiento": "2034-01-27",
  "Observaciones": "Persona ficticia con dos causas penales distintas."
 },
 {
  "ID": 141,
  "Nombre completo": "Daniela Cárdenas Galindo",
  "Expediente": "EXP-FIC-1980/2013",
  "Causa penal": "CP-FIC-240/2013",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Ciudad de México",
  "Circuito": "Primer Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito de Procesos Penales Federales en la Ciudad de México",
  "Lugar donde se encuentra": "Centro de Reinserción Norte (ficticio)",
  "Pena en años": 30,
  "Fecha de sentencia": "2015-07-22",
  "Fecha de inicio": "2013-08-03",
  "Fecha de cumplimiento": "2043-08-03",
  "Observaciones": "Solicitó beneficio de libertad anticipada (dato ficticio)."
 },
 {
  "ID": 142,
  "Nombre completo": "Samuel Garza Montes",
  "Expediente": "EXP-FIC-1987/2017",
  "Causa penal": "CP-FIC-241/2017",
  "Delito": "Contra la salud (transporte)",
  "Entidad Federativa": "Estado de México",
  "Circuito": "Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Materia Penal en el Estado de México",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Región Centro (ficticio)",
  "Pena en años": 4,
  "Fecha de sentencia": "2019-05-31",
  "Fecha de inicio": "2017-05-29",
  "Fecha de cumplimiento": "2021-05-28",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 143,
  "Nombre completo": "Karina Quintero Valencia",
  "Expediente": "EXP-FIC-1994/2015",
  "Causa penal": "CP-FIC-242/2015",
  "Delito": "Tráfico de personas",
  "Entidad Federativa": "Jalisco",
  "Circuito": "Tercer Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Materia Penal en Jalisco",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Occidente (ficticio)",
  "Pena en años": 15,
  "Fecha de sentencia": "2017-04-24",
  "Fecha de inicio": "2015-01-11",
  "Fecha de cumplimiento": "2030-01-11",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 144,
  "Nombre completo": "Isaac Fuentes Palacios",
  "Expediente": "EXP-FIC-2001/2022",
  "Causa penal": "CP-FIC-243/2022",
  "Delito": "Acopio de armas",
  "Entidad Federativa": "Nuevo León",
  "Circuito": "Cuarto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Nuevo León",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noreste (ficticio)",
  "Pena en años": 26,
  "Fecha de sentencia": "2022-10-30",
  "Fecha de inicio": "2022-02-03",
  "Fecha de cumplimiento": "2048-02-03",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 },
 {
  "ID": 145,
  "Nombre completo": "Cecilia Galindo Mejía",
  "Expediente": "EXP-FIC-2008/2023",
  "Causa penal": "CP-FIC-244/2023",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Sonora",
  "Circuito": "Quinto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sonora",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Desierto (ficticio)",
  "Pena en años": 9,
  "Fecha de sentencia": "2024-04-09",
  "Fecha de inicio": "2023-04-27",
  "Fecha de cumplimiento": "2032-04-27",
  "Observaciones": "Sentencia firme. Registro de prueba."
 },
 {
  "ID": 146,
  "Nombre completo": "Silvia Palacios Lozano",
  "Expediente": "EXP-FIC-2015/2017",
  "Causa penal": "CP-FIC-245/2017",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Puebla",
  "Circuito": "Sexto Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Materia Penal en Puebla",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Los Volcanes (ficticio)",
  "Pena en años": 17,
  "Fecha de sentencia": "2018-07-17",
  "Fecha de inicio": "2017-08-25",
  "Fecha de cumplimiento": "2034-08-25",
  "Observaciones": "Pena compurgada parcialmente en prisión preventiva (dato ficticio)."
 },
 {
  "ID": 147,
  "Nombre completo": "Gerardo Bautista Robles",
  "Expediente": "EXP-FIC-2022/2021",
  "Causa penal": "CP-FIC-246/2021",
  "Delito": "Falsificación de moneda",
  "Entidad Federativa": "Veracruz",
  "Circuito": "Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Tercero de Distrito en Veracruz",
  "Lugar donde se encuentra": "Centro Estatal de Reinserción Golfo (ficticio)",
  "Pena en años": 29,
  "Fecha de sentencia": "2023-06-05",
  "Fecha de inicio": "2021-07-08",
  "Fecha de cumplimiento": "2050-07-08",
  "Observaciones": "Se encuentra en trámite un incidente de traslado (dato ficticio)."
 },
 {
  "ID": 148,
  "Nombre completo": "Juan Pablo Barrios Medina",
  "Expediente": "EXP-FIC-2029/2012",
  "Causa penal": "CP-FIC-247/2012",
  "Delito": "Portación de arma de fuego de uso exclusivo",
  "Entidad Federativa": "Michoacán",
  "Circuito": "Décimo Primer Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Michoacán",
  "Lugar donde se encuentra": "Centro Regional Lago Azul (ficticio)",
  "Pena en años": 2,
  "Fecha de sentencia": "2014-02-05",
  "Fecha de inicio": "2012-06-05",
  "Fecha de cumplimiento": "2014-06-05",
  "Observaciones": "Interpuso recurso de apelación; pendiente de resolución (dato ficticio)."
 },
 {
  "ID": 149,
  "Nombre completo": "Adrián Miranda Cabrera",
  "Expediente": "EXP-FIC-2036/2016",
  "Causa penal": "CP-FIC-248/2016",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Sinaloa",
  "Circuito": "Décimo Segundo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Sinaloa",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Noroeste (ficticio)",
  "Pena en años": 20,
  "Fecha de sentencia": "2018-01-10",
  "Fecha de inicio": "2016-11-20",
  "Fecha de cumplimiento": "2036-11-20",
  "Observaciones": "Cuenta con otra causa penal en trámite (dato ficticio)."
 },
 {
  "ID": 150,
  "Nombre completo": "Yolanda Zamora Zavala",
  "Expediente": "EXP-FIC-2043/2014",
  "Causa penal": "CP-FIC-249/2014",
  "Delito": "Delincuencia organizada",
  "Entidad Federativa": "Chihuahua",
  "Circuito": "Décimo Séptimo Circuito",
  "Juzgado de Distrito": "Juzgado Primero de Distrito en Chihuahua",
  "Lugar donde se encuentra": "Centro Federal de Reinserción Frontera (ficticio)",
  "Pena en años": 22,
  "Fecha de sentencia": "2015-09-11",
  "Fecha de inicio": "2014-11-21",
  "Fecha de cumplimiento": "2036-11-21",
  "Observaciones": "Requiere verificación de domicilio procesal (dato ficticio)."
 }
];
